// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPVP_PAm8lk31xlCaW7WUUFT6Q_bOKrBQ',
    appId: '1:334429705416:web:7489d133c4daee778ac1fd',
    messagingSenderId: '334429705416',
    projectId: 'fir-flutter-codelab-2093e',
    authDomain: 'fir-flutter-codelab-2093e.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-2093e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPt5iGpNz3zCQmcTI3RFJUxjjnUl_ReqE',
    appId: '1:334429705416:android:0d6dc4968805c2ed8ac1fd',
    messagingSenderId: '334429705416',
    projectId: 'fir-flutter-codelab-2093e',
    storageBucket: 'fir-flutter-codelab-2093e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfjSnXCybFRnYQ0wte_C938F_E455tQ84',
    appId: '1:334429705416:ios:a3342bf86cdd3d3f8ac1fd',
    messagingSenderId: '334429705416',
    projectId: 'fir-flutter-codelab-2093e',
    storageBucket: 'fir-flutter-codelab-2093e.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfjSnXCybFRnYQ0wte_C938F_E455tQ84',
    appId: '1:334429705416:ios:a3342bf86cdd3d3f8ac1fd',
    messagingSenderId: '334429705416',
    projectId: 'fir-flutter-codelab-2093e',
    storageBucket: 'fir-flutter-codelab-2093e.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
